### ISSUE TITLE
Add LA city data to web map

### ISSUE THREAD

**Issue by matikin9** [rhubarb-crew/la-region-library-map#2]

**Comment by eirinikos** [comment]
Made an attempt with [today's commit](https://github.com/rhubarb-crew/la-region-library-map/commit/fc25a9a03472440ee30e32602c8b4d1a703e830c)... (all new code is commented out for the time being, though).

From line 53 and on, I used JS to iterate through the City's JSON data.

Lines 30-51 are an emulation of your jQuery code to iterate through the data.

Ack!

**Comment by eirinikos** [comment]
Closed with [this commit](https://github.com/rhubarb-crew/la-region-library-map/commit/b946d258cae44ca45dbee4489181672cef834c30). :balloon:
